version: '3'
services:
  php.dev:
    image: slothdevdocker/php:8.2-debian-apache-dev
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8080}:8080'
    volumes:
      - '.:/app'
    depends_on:
      - postgres
    environment:
      HTTP_PORT: 8080

  postgres:
    image: postgres:latest
    volumes:
      - 'sail-postgres:/var/lib/postgresql/data'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - '${FORWARD_PGADMIN_PORT:-8081}:80'
    volumes:
      - sail-pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  sail-pgadmin:
    driver: local
  sail-postgres:
    driver: local
